### ISSUE TITLE
Reorganize test

### ISSUE THREAD

**Issue by joelcox** [joelcox/codeigniter-redis#10]
I just migrated the unit test controller to PHPUnit, but the quality of these tests is seriously lacking. These tests are rather integration tests (black box approach) rather than proper unit tests.

**Comment by joelcox** [comment]
I wrote some thorough tests for `_encode_request` in 0c523477632f95204780cf00cd9a5e4dcac139b0, but `_read_request()` is currently untestable on its own. Some smoke tests are still in place, which I fleshed out a bit.

**Comment by ghost** [comment]
I just threw a `DEBUG SEGFAULT`, we need to handle the socket closing unexpectedly.  Ouch.

**Comment by joelcox** [comment]
How can this be reproduced? Shutting down `redis-server` in the middle of a request?

**Comment by ghost** [comment]
By closing the socket randomly if a variable is passed to the constructor (which would only happen in test cases).  Otherwise, it's just a check against NULL, perhaps if some constant is defined.

**Comment by ghost** [comment]
Redis not working _is_ recoverable in some instances. I need to have a think about how to handle it, and the 'how' could be tested :)

**Comment by joelcox** [comment]
So by creating multiple instances of the Redis class? Sorry, I'm not following you.

**Comment by ghost** [comment]
Sorry, this would be more work than worth it. What I was hoping to be able to do is handle (gracefully) instances where Redis just _dies_. You can see it's a bit icky by adding a temporary method to close the socket midway through, so I thought of adding a user defined callback (also handy for testing) that could tell an app to stop using Redis.

More overhead and work than it's really worth at present especially for a library that implements the entire command set without any actual concrete methods :)

**Comment by ghost** [comment]
I'll add proper tests for transactions shortly (though those are mostly integration tests), I need to tickle [WATCH](http://redis.io/commands/watch) during transactions as well. I'm quite happy at this point, everything 'just works' :)

**Comment by joelcox** [comment]
Haha. Great job.

**Comment by ghost** [comment]
Well, I went through and tried various commands in various scenarios differently and everything works (or fails) as expected.  But really, all we're doing beyond what we have is testing Redis itself, which Redis does quite a good job of doing already :)

I can properize a simple test for transactions if you really want to include them. But honestly, the tests we have seem sufficient. We'll know quickly if a change broke encoding / decoding of the wire protocol .. anything else is really just exercising Redis.

**Comment by joelcox** [comment]
Agreed. I think we covered most (if not all) the encoding cases. Everything else is beyond our responsibility. I'll close this for now.
