### ISSUE TITLE
Multi line bulk responses are truncated by _bulk_reply()

### ISSUE THREAD

**Issue by ghost** [joelcox/codeigniter-redis#15]
In `_bulk_reply()` , we test for the number of bytes to read from the initial response, and then attempt to read that response via `fgets()`. The problem is, if the bulk reply is the result of a command like `INFO`, the response will be truncated as soon as the first `\r\n` is encountered.

Simply changing `fgets()` to `fread()` in that function fixes it, as `fread()` will simply read the requested length, however a call to `rtrim()` is needed to remove the right most `\r\n`.

All tests pass once that's done, and multi line replies (that aren't multi bulk replies) return as expected. Do you want a pull request for this? It's extremely trivial. I was halfway considering implementing a concrete `info()` method to break it down into a nice convenient array (I probably will, I'm just not sure if you want it or not). 

Cheers!
--Tim

**Comment by joelcox** [comment]
The real question is, why does the Redis protocol reply with a bulk reply instead of a nice multi line bulk?!

**Comment by ghost** [comment]
I'm .. rather .. scratching my head on that too. Presumably, even shell scripts should be able to parse the `INFO` output, which also explains the way it's commented, and someone did come up with a collection of BASH functions to use Redis.

**Comment by joelcox** [comment]
Ah well. What about this?

https://github.com/joelcox/codeigniter-redis/commit/a7776b482af1a1316e4db56eeda563f2a7637f3a

**Comment by ghost** [comment]
Almost identical to what I was about to push. That works, please merge it into develop.

**Comment by joelcox** [comment]
Done.

**Comment by ghost** [comment]
Ey, note that `$parts[1]` does not exist if the returned line is a comment. Need to check if `$parts[1]` is set before using it. Sorry I missed that, I just wasn't used to responses returning comments :)

**Comment by joelcox** [comment]
Ah, a comment in info? How would this be set? My INFO returned a nice clean list, so I didn't consider this.

**Comment by ghost** [comment]
This is a partial dump of my output on my dev box (running the latest redis RC):

```
redis 127.0.0.1:6379> INFO
# Server
redis_version:2.5.9
redis_git_sha1:00000000
redis_git_dirty:0
os:Linux 2.6.18-274.12.1.el5xen x86_64
arch_bits:64
multiplexing_api:epoll
gcc_version:4.1.2
process_id:25360
run_id:0348359726b6a68fcf5ac070db7bcce7f520aa85
tcp_port:6379
uptime_in_seconds:896604
uptime_in_days:10
lru_clock:1601421

# Clients
connected_clients:1
client_longest_output_list:0
client_biggest_input_buf:0
blocked_clients:0

# Memory
```

Somehow I remember them being in 2.4.13, but I could definitely be incorrect - I don't pay much attention to what changed except for the major changes that Salvatore tweets. Anyway, they're definitely in 2.6.0-rc3 ... so that simple check future proofs things a bit.

**Comment by joelcox** [comment]
No sign of these comments in 2.4.13.

**Comment by joelcox** [comment]
https://github.com/joelcox/codeigniter-redis/commit/6f78c1e56bf4a40e7276eac2c494788831fae276
