### ISSUE TITLE
Commands with 3+ arguments don't work

### ISSUE THREAD

**Issue by danhunsaker** [joelcox/codeigniter-redis#19]
I attempted to use `SETEX` and found, to my dismay, that it wasn't getting all of the arguments it wanted.  Upon inspection of the `__call()` method, I quickly discovered why.  I have a simple fix for this, which I will issue a pull request for in just a minute.  I don't think it will fix Issue #18 (though it might provide a cleaner workaround), so I'm creating a new issue for it here.

Basically, the fix is to use `implode()` on the arguments array, since the logic in `_encode_request()` already properly handles an argument list separated by spaces.  This is only done, of course, if the first argument is _not_ an array.  The second argument to `_encode_request()` is not sent in this case.

**Comment by joelcox** [comment]
Closed per #20. Thanks again.
