### ISSUE TITLE
Remove plaintext commands

### ISSUE THREAD

**Issue by joelcox** [joelcox/codeigniter-redis#23]
v0.4 will remove plaintext commands for methods, except via the `Redis::command` method. This will break the current API, but I don't suspect that many people will be affected, due to the overloading capabilities of the library.

**Comment by danhunsaker** [comment]
I don't follow.  What's being changed, specifically?

**Comment by joelcox** [comment]
Currently it's possible to do things like `$this->redid->set('foo bar');` I'm proposing to get rid of this syntax and only allow the different tokens passed as individual arguments: `$this->redis->set('foo', 'bar')`. The single string notation would still be accessible through `$this->redis->command('SET foo bar');`

**Comment by danhunsaker** [comment]
Ah, that makes sense.  Of course, it only works because of the internal logic being employed to pass data around within the class, but that can be changed as well, and as easily.

**Comment by joelcox** [comment]
So I [implemented this change](https://github.com/joelcox/codeigniter-redis/tree/remove-plain-text) and I'm pretty pleased with the result. Some weird edge cases have been eliminated and this resulted in much cleaner code IMHO.

I marked several tests that showed the working of the old syntax as follows: `$this->markTestIncomplete('This syntax is no longer supported.');`. All other tests seem to pass flawlessly, but it required a bit of rewriting because of new internal method headers.

Please let me know what you guys think of this.

**Comment by joelcox** [comment]
Fixed in 7114eb877aae1bc095c3458a5fed7c4067e49997
