### ISSUE TITLE
In the Constructor, connection error should show $config['port']

### ISSUE THREAD

**Issue by beckleyworks** [joelcox/codeigniter-redis#36]
// Display an error message if connection failed
if ( ! $this->_connection)
{
    show_error('Could not connect to Redis at ' . $config['host'] . ':' . $config['redis_port']);
}

should be $config['port'] instead, right? the port wasn't appearing in the error message for me.

**Comment by joelcox** [comment]
Great catch Beckley. Looks like I messed up renaming the keys in this commit. 773d846e8b9275723ca02d1155013f0ff7e8aba4
