### ISSUE TITLE
Some data does not properly return from redis

### ISSUE THREAD

**Issue by integrii** [joelcox/codeigniter-redis#39]
Here is a test
$data = "ImE6MzA6e2k6MDthOjc6e3M6MjpcImlkXCI7czo1OlwiNDYwMTdcIjtzOjQ6XCJuYW1lXCI7czo5OlwiS2VubnlkYWxlXCI7czo4OlwibGF0aXR1ZGVcIjtzOjk6XCI0Ny41MTU0MThcIjtzOjk6XCJsb25naXR1ZGVcIjtzOjExOlwiLTEyMi4xOTg2MTRcIjtzOjQ6XCJ0aW1lXCI7aToxMzc2MDMxMDk5O3M6NDpcImNpdHlcIjtzOjY6XCJSZW50b25cIjtzOjU6XCJzdGF0ZVwiO3M6MjpcIldBXCI7fWk6MTthOjc6e3M6MjpcImlkXCI7czo1OlwiNDk1MzJcIjtzOjQ6XCJuYW1lXCI7czo5OlwiTWFwbGV3b29kXCI7czo4OlwibGF0aXR1ZGVcIjtzOjk6XCI0Ny40NjkzODJcIjtzOjk6XCJsb25naXR1ZGVcIjtzOjExOlwiLTEyMi4xNjQzNzZcIjtzOjQ6XCJ0aW1lXCI7aToxMzc2MDMxMDk5O3M6NDpcImNpdHlcIjtzOjY6XCJSZW50b25cIjtzOjU6XCJzdGF0ZVwiO3M6MjpcIldBXCI7fWk6MjthOjc6e3M6MjpcImlkXCI7czo2OlwiMjExMDM2XCI7czo0OlwibmFtZVwiO3M6NzpcIkdsZW5jb2VcIjtzOjg6XCJsYXRpdHVkZVwiO3M6OTpcIjQ3LjUxMTE5OFwiO3M6OTpcImxvbmdpdHVkZVwiO3M6MTE6XCItMTIyLjE2MzU4MVwiO3M6NDpcInRpbWVcIjtpOjEzNzYwMzEwOTk7czo0OlwiY2l0eVwiO3M6NjpcIlJlbnRvblwiO3M6NTpcInN0YXRlXCI7czoyOlwiV0FcIjt9aTozO2E6Nzp7czoyOlwiaWRcIjtzOjY6XCIyNDA3NzBcIjtzOjQ6XCJuYW1lXCI7czo2OlwiU3Vuc2V0XCI7czo4OlwibGF0aXR1ZGVcIjtzOjk6XCI0Ny41MDI0MTFcIjtzOjk6XCJsb25naXR1ZGVcIjtzOjExOlwiLTEyMi4xODU4NTRcIjtzOjQ6XCJ0aW1lXCI7aToxMzc2MDMxMDk5O3M6NDpcImNpdHlcIjtzOjY6XCJSZW50b25cIjtzOjU6XCJzdGF0ZVwiO3M6MjpcIldBXCI7fWk6NDthOjc6e3M6MjpcImlkXCI7czo2OlwiMjUxMjU2XCI7czo0OlwibmFtZVwiO3M6OTpcIk1heSBDcmVla1wiO3M6ODpcImxhdGl0dWRlXCI7czo5OlwiNDcuNTA5MjAzXCI7czo5OlwibG9uZ2l0dWRlXCI7czoxMTpcIi0xMjIuMTU3NzE3XCI7czo0OlwidGltZVwiO2k6MTM3NjAzMTA5OTtzOjQ6XCJjaXR5XCI7czo2OlwiUmVudG9uXCI7czo1Olwic3RhdGVcIjtzOjI6XCJXQVwiO31pOjU7YTo3OntzOjI6XCJpZFwiO3M6NjpcIjI1MTUzNFwiO3M6NDpcIm5hbWVcIjtzOjg6XCJPcmNoYXJkc1wiO3M6ODpcImxhdGl0dWRlXCI7czo5OlwiNDcuNDk0MDIxXCI7czo5OlwibG9uZ2l0dWRlXCI7czoxMTpcIi0xMjIuMTYwNDM5XCI7czo0OlwidGltZVwiO2k6MTM3NjAzMTA5OTtzOjQ6XCJjaXR5XCI7czo2OlwiUmVudG9uXCI7czo1Olwic3RhdGVcIjtzOjI6XCJXQVwiO31pOjY7YTo3OntzOjI6XCJpZFwiO3M6NjpcIjI1MzUwNVwiO3M6NDpcIm5hbWVcIjtzOjg6XCJMYUNyb3NzZVwiO3M6ODpcImxhdGl0dWRlXCI7czo4OlwiNDcuNTIyMzdcIjtzOjk6XCJsb25naXR1ZGVcIjtzOjExOlwiLTEyMi4xOTE3MjdcIjtzOjQ6XCJ0aW1lXCI7aToxMzc2MDMxMDk5O3M6NDpcImNpdHlcIjtzOjY6XCJSZW50b25cIjtzOjU6XCJzdGF0ZVwiO3M6MjpcIldBXCI7fWk6NzthOjc6e3M6MjpcImlkXCI7czo2OlwiMjcyNDkyXCI7czo0OlwibmFtZVwiO3M6MTE6XCJTb3V0aCBVbmlvblwiO3M6ODpcImxhdGl0dWRlXCI7czo5OlwiNDcuNDg0OTY5XCI7czo5OlwibG9uZ2l0dWRlXCI7czoxMDpcIi0xMjIuMTYwMTdcIjtzOjQ6XCJ0aW1lXCI7aToxMzc2MDMxMDk5O3M6NDpcImNpdHlcIjtzOjY6XCJSZW50b25cIjtzOjU6XCJzdGF0ZVwiO3M6MjpcIldBXCI7fWk6ODthOjc6e3M6MjpcImlkXCI7czo2OlwiMjc1NTkwXCI7czo0OlwibmFtZVwiO3M6OTpcIlN0b25lZ2F0ZVwiO3M6ODpcImxhdGl0dWRlXCI7czo5OlwiNDcuNTExODMxXCI7czo5OlwibG9uZ2l0dWRlXCI7czoxMTpcIi0xMjIuMTQ1OTA4XCI7czo0OlwidGltZVwiO2k6MTM3NjAzMTA5OTtzOjQ6XCJjaXR5XCI7czo2OlwiUmVudG9uXCI7czo1Olwic3RhdGVcIjtzOjI6XCJXQVwiO31pOjk7YTo3OntzOjI6XCJpZFwiO3M6NjpcIjM5NjE1MVwiO3M6NDpcIm5hbWVcIjtzOjc6XCJDYXNjYWRlXCI7czo4OlwibGF0aXR1ZGVcIjtzOjk6XCI0Ny40NTI0OTJcIjtzOjk6XCJsb25naXR1ZGVcIjtzOjExOlwiLTEyMi4xODU5MTVcIjtzOjQ6XCJ0aW1lXCI7aToxMzc2MDMxMDk5O3M6NDpcImNpdHlcIjtzOjY6XCJSZW50b25cIjtzOjU6XCJzdGF0ZVwiO3M6MjpcIldBXCI7fWk6MTA7YTo3OntzOjI6XCJpZFwiO3M6NjpcIjYyMzM1MFwiO3M6NDpcIm5hbWVcIjtzOjEyOlwiU291dGggUmVudG9uXCI7czo4OlwibGF0aXR1ZGVcIjtzOjk6XCI0Ny40Nzc1NzFcIjtzOjk6XCJsb25naXR1ZGVcIjtzOjExOlwiLTEyMi4yMTA1ODZcIjtzOjQ6XCJ0aW1lXCI7aToxMzc2MDMxMDk5O3M6NDpcImNpdHlcIjtzOjY6XCJSZW50b25cIjtzOjU6XCJzdGF0ZVwiO3M6MjpcIldBXCI7fWk6MTE7YTo3OntzOjI6XCJpZFwiO3M6NjpcIjYyMzM1MVwiO3M6NDpcIm5hbWVcIjtzOjE1OlwiRWFybGluZ3RvbiBIaWxsXCI7czo4OlwibGF0aXR1ZGVcIjtzOjk6XCI0Ny40ODc0MTZcIjtzOjk6XCJsb25naXR1ZGVcIjtzOjExOlwiLTEyMi4yMjI1MzZcIjtzOjQ6XCJ0aW1lXCI7aToxMzc2MDMxMDk5O3M6NDpcImNpdHlcIjtzOjY6XCJSZW50b25cIjtzOjU6XCJzdGF0ZVwiO3M6MjpcIldBXCI7fWk6MTI7YTo3OntzOjI6XCJpZFwiO3M6NjpcIjYyMzM1MlwiO3M6NDpcIm5hbWVcIjtzOjEyOlwiTm9ydGggUmVudG9uXCI7czo4OlwibGF0aXR1ZGVcIjtzOjk6XCI0Ny40ODcyMDhcIjtzOjk6XCJsb25naXR1ZGVcIjtzOjExOlwiLTEyMi4yMDA2NTdcIjtzOjQ6XCJ0aW1lXCI7aToxMzc2MDMxMDk5O3M6NDpcImNpdHlcIjtzOjY6XCJSZW50b25cIjtzOjU6XCJzdGF0ZVwiO3M6MjpcIldBXCI7fWk6MTM7YTo3OntzOjI6XCJpZFwiO3M6NjpcIjYyMzM1M1wiO3M6NDpcIm5hbWVcIjtzOjEzOlwiTGliZXJ0eSBSaWRnZVwiO3M6ODpcImxhdGl0dWRlXCI7czo4OlwiNDcuNDgxODdcIjtzOjk6XCJsb25naXR1ZGVcIjtzOjExOlwiLTEyMi4xODQxMTdcIjtzOjQ6XCJ0aW1lXCI7aToxMzc2MDMxMDk5O3M6NDpcImNpdHlcIjtzOjY6XCJSZW50b25cIjtzOjU6XCJzdGF0ZVwiO3M6MjpcIldBXCI7fWk6MTQ7YTo3OntzOjI6XCJpZFwiO3M6NjpcIjYyMzM1NFwiO3M6NDpcIm5hbWVcIjtzOjE0OlwiTWFwbGV3b29kIEdsZW5cIjtzOjg6XCJsYXRpdHVkZVwiO3M6OTpcIjQ3LjQ3NTU3NFwiO3M6OTpcImxvbmdpdHVkZVwiO3M6MTE6XCItMTIyLjE3NDYzMVwiO3M6NDpcInRpbWVcIjtpOjEzNzYwMzEwOTk7czo0OlwiY2l0eVwiO3M6NjpcIlJlbnRvblwiO3M6NTpcInN0YXRlXCI7czoyOlwiV0FcIjt9aToxNTthOjc6e3M6MjpcImlkXCI7czo2OlwiNjIzMzU1XCI7czo0OlwibmFtZVwiO3M6MTU6XCJMZWlzdXJlIEVzdGF0ZXNcIjtzOjg6XCJsYXRpdHVkZVwiO3M6OTpcIjQ3LjQ4MzE0N1wiO3M6OTpcImxvbmdpdHVkZVwiO3M6MTE6XCItMTIyLjE2Njg5OFwiO3M6NDpcInRpbWVcIjtpOjEzNzYwMzEwOTk7czo0OlwiY2l0eVwiO3M6NjpcIlJlbnRvblwiO3M6NTpcInN0YXRlXCI7czoyOlwiV0FcIjt9aToxNjthOjc6e3M6MjpcImlkXCI7czo2OlwiNjIzMzU2XCI7czo0OlwibmFtZVwiO3M6MTM6XCJIZWF0aGVyIERvd25zXCI7czo4OlwibGF0aXR1ZGVcIjtzOjk6XCI0Ny40NzkzNDZcIjtzOjk6XCJsb25naXR1ZGVcIjtzOjEwOlwiLTEyMi4xNjAxN1wiO3M6NDpcInRpbWVcIjtpOjEzNzYwMzEwOTk7czo0OlwiY2l0eVwiO3M6NjpcIlJlbnRvblwiO3M6NTpcInN0YXRlXCI7czoyOlwiV0FcIjt9aToxNzthOjc6e3M6MjpcImlkXCI7czo2OlwiNjIzMzU3XCI7czo0OlwibmFtZVwiO3M6MTU6XCJPbmUgVW5pb24gUGxhY2VcIjtzOjg6XCJsYXRpdHVkZVwiO3M6OTpcIjQ3LjQ4NDkwN1wiO3M6OTpcImxvbmdpdHVkZVwiO3M6MTA6XCItMTIyLjE1NDg5XCI7czo0OlwidGltZVwiO2k6MTM3NjAzMTA5OTtzOjQ6XCJjaXR5XCI7czo2OlwiUmVudG9uXCI7czo1Olwic3RhdGVcIjtzOjI6XCJXQVwiO31pOjE4O2E6Nzp7czoyOlwiaWRcIjtzOjY6XCI2MjMzNThcIjtzOjQ6XCJuYW1lXCI7czo4OlwiV2luZHNvbmdcIjtzOjg6XCJsYXRpdHVkZVwiO3M6OTpcIjQ3LjQ4OTM2OVwiO3M6OTpcImxvbmdpdHVkZVwiO3M6MTE6XCItMTIyLjE1MTY2NlwiO3M6NDpcInRpbWVcIjtpOjEzNzYwMzEwOTk7czo0OlwiY2l0eVwiO3M6NjpcIlJlbnRvblwiO3M6NTpcInN0YXRlXCI7czoyOlwiV0FcIjt9aToxOTthOjc6e3M6MjpcImlkXCI7czo2OlwiNjIzMzU5XCI7czo0OlwibmFtZVwiO3M6OTpcIlZpbmV5YXJkc1wiO3M6ODpcImxhdGl0dWRlXCI7czo5OlwiNDcuNDkyNTQ2XCI7czo5OlwibG9uZ2l0dWRlXCI7czoxMTpcIi0xMjIuMTYyOTExXCI7czo0OlwidGltZVwiO2k6MTM3NjAzMTA5OTtzOjQ6XCJjaXR5XCI7czo2OlwiUmVudG9uXCI7czo1Olwic3RhdGVcIjtzOjI6XCJXQVwiO31pOjIwO2E6Nzp7czoyOlwiaWRcIjtzOjY6XCI2MjMzNjBcIjtzOjQ6XCJuYW1lXCI7czo4OlwiVmVyQ2VsbG9cIjtzOjg6XCJsYXRpdHVkZVwiO3M6OTpcIjQ3LjQ5Njk4NVwiO3M6OTpcImxvbmdpdHVkZVwiO3M6MTA6XCItMTIyLjE0ODk4XCI7czo0OlwidGltZVwiO2k6MTM3NjAzMTA5OTtzOjQ6XCJjaXR5XCI7czo2OlwiUmVudG9uXCI7czo1Olwic3RhdGVcIjtzOjI6XCJXQVwiO31pOjIxO2E6Nzp7czoyOlwiaWRcIjtzOjY6XCI2MjMzNjFcIjtzOjQ6XCJuYW1lXCI7czoxMDpcIkFzcGVud29vZHNcIjtzOjg6XCJsYXRpdHVkZVwiO3M6OTpcIjQ3LjQ5NjYxMVwiO3M6OTpcImxvbmdpdHVkZVwiO3M6MTE6XCItMTIyLjE0OTg5MVwiO3M6NDpcInRpbWVcIjtpOjEzNzYwMzEwOTk7czo0OlwiY2l0eVwiO3M6NjpcIlJlbnRvblwiO3M6NTpcInN0YXRlXCI7czoyOlwiV0FcIjt9aToyMjthOjc6e3M6MjpcImlkXCI7czo2OlwiNjIzMzYyXCI7czo0OlwibmFtZVwiO3M6MTA6XCJBc3RlciBQYXJrXCI7czo4OlwibGF0aXR1ZGVcIjtzOjk6XCI0Ny41MDQxOTJcIjtzOjk6XCJsb25naXR1ZGVcIjtzOjExOlwiLTEyMi4xNDQ2NThcIjtzOjQ6XCJ0aW1lXCI7aToxMzc2MDMxMDk5O3M6NDpcImNpdHlcIjtzOjY6XCJSZW50b25cIjtzOjU6XCJzdGF0ZVwiO3M6MjpcIldBXCI7fWk6MjM7YTo3OntzOjI6XCJpZFwiO3M6NjpcIjYyMzM2M1wiO3M6NDpcIm5hbWVcIjtzOjEwOlwiU3VtbWVyd2luZFwiO3M6ODpcImxhdGl0dWRlXCI7czo4OlwiNDcuNTA4NDJcIjtzOjk6XCJsb25naXR1ZGVcIjtzOjExOlwiLTEyMi4xNTIzMDNcIjtzOjQ6XCJ0aW1lXCI7aToxMzc2MDMxMDk5O3M6NDpcImNpdHlcIjtzOjY6XCJSZW50b25cIjtzOjU6XCJzdGF0ZVwiO3M6MjpcIldBXCI7fWk6MjQ7YTo3OntzOjI6XCJpZFwiO3M6NjpcIjYyMzM2NFwiO3M6NDpcIm5hbWVcIjtzOjEwOlwiU3ByaW5ndHJlZVwiO3M6ODpcImxhdGl0dWRlXCI7czo5OlwiNDcuNTA1MTE1XCI7czo5OlwibG9uZ2l0dWRlXCI7czoxMTpcIi0xMjIuMTYyMDM5XCI7czo0OlwidGltZVwiO2k6MTM3NjAzMTA5OTtzOjQ6XCJjaXR5XCI7czo2OlwiUmVudG9uXCI7czo1Olwic3RhdGVcIjtzOjI6XCJXQVwiO31pOjI1O2E6Nzp7czoyOlwiaWRcIjtzOjY6XCI2MjMzNjVcIjtzOjQ6XCJuYW1lXCI7czoxNjpcIkhvbmV5IENyZWVrIFBhcmtcIjtzOjg6XCJsYXRpdHVkZVwiO3M6OTpcIjQ3LjUwNzY2NVwiO3M6OTpcImxvbmdpdHVkZVwiO3M6MTE6XCItMTIyLjE3MzMzNVwiO3M6NDpcInRpbWVcIjtpOjEzNzYwMzEwOTk7czo0OlwiY2l0eVwiO3M6NjpcIlJlbnRvblwiO3M6NTpcInN0YXRlXCI7czoyOlwiV0FcIjt9aToyNjthOjc6e3M6MjpcImlkXCI7czo2OlwiNjIzMzY2XCI7czo0OlwibmFtZVwiO3M6MTc6XCJIb25leSBDcmVlayBSaWRnZVwiO3M6ODpcImxhdGl0dWRlXCI7czo5OlwiNDcuNTE0MDY4XCI7czo5OlwibG9uZ2l0dWRlXCI7czoxMTpcIi0xMjIuMTc0NjE0XCI7czo0OlwidGltZVwiO2k6MTM3NjAzMTA5OTtzOjQ6XCJjaXR5XCI7czo2OlwiUmVudG9uXCI7czo1Olwic3RhdGVcIjtzOjI6XCJXQVwiO31pOjI3O2E6Nzp7czoyOlwiaWRcIjtzOjY6XCI2MjMzNjdcIjtzOjQ6XCJuYW1lXCI7czoxNDpcIlByZXNpZGVudCBQYXJrXCI7czo4OlwibGF0aXR1ZGVcIjtzOjk6XCI0Ny40OTczMTRcIjtzOjk6XCJsb25naXR1ZGVcIjtzOjExOlwiLTEyMi4xNzA4NzlcIjtzOjQ6XCJ0aW1lXCI7aToxMzc2MDMxMDk5O3M6NDpcImNpdHlcIjtzOjY6XCJSZW50b25cIjtzOjU6XCJzdGF0ZVwiO3M6MjpcIldBXCI7fWk6Mjg7YTo3OntzOjI6XCJpZFwiO3M6NjpcIjYyMzM2OFwiO3M6NDpcIm5hbWVcIjtzOjEzOlwiSGlnaGJ1cnkgUGFya1wiO3M6ODpcImxhdGl0dWRlXCI7czo5OlwiNDcuNDg5NzQzXCI7czo5OlwibG9uZ2l0dWRlXCI7czoxMTpcIi0xMjIuMTgzMDg4XCI7czo0OlwidGltZVwiO2k6MTM3NjAzMTA5OTtzOjQ6XCJjaXR5XCI7czo2OlwiUmVudG9uXCI7czo1Olwic3RhdGVcIjtzOjI6XCJXQVwiO31pOjI5O2E6Nzp7czoyOlwiaWRcIjtzOjY6XCI2MjMzNjlcIjtzOjQ6XCJuYW1lXCI7czoxMjpcIkNsdm9lciBDcmVla1wiO3M6ODpcImxhdGl0dWRlXCI7czo5OlwiNDcuNTE1NTg1XCI7czo5OlwibG9uZ2l0dWRlXCI7czoxMTpcIi0xMjIuMjA1MDQ3XCI7czo0OlwidGltZVwiO2k6MTM3NjAzMTA5OTtzOjQ6XCJjaXR5XCI7czo2OlwiUmVudG9uXCI7czo1Olwic3RhdGVcIjtzOjI6XCJXQVwiO319Ig=="

$this->redis->set("test", $data);

$brokenData = $this->redis->get("test");

echo $brokenData;

the data you see will be cut off.

**Comment by integrii** [comment]
Lost a few nights of my life over this one.

**Comment by integrii** [comment]
actually, it appears this was fixed in a recent revision.  The fix is in _bulk_reply

**Comment by integrii** [comment]
I take it back.  Something is still wrong with the updated code.  It makes complete sense when you read it, but if you hit the refresh button many times - it will have some replies with missing data!

**Comment by integrii** [comment]
Here is the proof.  I added the following code to _bulk_reply() and hit refresh a lot.  When the code looked like it had a missing chunk on the page, it had a missing chunk in the logs to.  The data was for some reason at the end of the response still.  The value_length seems to be accurate even with the missing data, so something weird is going on.
error_log($response);   
$response .= fgets($this->_connection);
error_log($response);

![image](https://f.cloud.github.com/assets/98695/937006/c63031ae-00cb-11e3-9265-9d798a9181c9.png)

**Comment by integrii** [comment]
https://github.com/joelcox/codeigniter-redis/pull/40 fixed this issue.

**Comment by joelcox** [comment]
Hey everyone. Sorry for not responding to this issue earlier; I've been overseas for 6 weeks without a computer. Thanks for pitching in Dan.
