### ISSUE TITLE
Set json string as value

### ISSUE THREAD

**Issue by jonathanwiesel** [joelcox/codeigniter-redis#41]
I'm trying the following

$value = json_encode($jsonArrayed);
$response = $redis->command('set test ' .$value);

But I get bad syntax error.
I've also tried with 

$value = '\''.json_encode($jsonArrayed).'\'';
$value = '\''.addslashes(json_encode($jsonArrayed)).'\'';

But no luck.

Any idea how to set a json string as a value?

**Comment by danhunsaker** [comment]
Generally speaking, your string should be quoted in the `command()` string, so `$redis->command('set test "' . $value . '"');` would be your function call.

That said, using `command()` is not the preferred method of using CI-Redis - instead, use `$redis->set('test', $value);` and the class will take care of all the escaping and other such tricks on your behalf.

**Comment by danhunsaker** [comment]
(Also, it should be `$this->redis->set(...)` instead of `$redis->set(...)`, but I'm guessing you know that, working with CI...)

**Comment by jonathanwiesel** [comment]
Thank you very much, dumb of me, I should have tried using the `set` function in the first place, worked perfectly. 

About the use of `$redis->...` instead of `$this->redis->...` was because I implemented a constructor in the library and was using the $redis variable for the object:

<pre>
$redis = new CI_Redis();
</pre>

**Comment by jonathanwiesel** [comment]
I noticed that setting a json as a value went good. 

However when I try to get it, the response becomes truncated (no fixed size), one with more than 3500 characters came good but other with 2800 was truncated. 

Looking at the database through the terminal I can see that the values are indeed complete so the truncation process may be happening in the parser that receives the 'get' call back to CodeIgniter.

**Comment by danhunsaker** [comment]
See issues #39 and #40...
