### ISSUE TITLE
test_empty_hash_values fails after changing bulk reply code

### ISSUE THREAD

**Issue by joelcox** [joelcox/codeigniter-redis#43]
See issue #33, #40, #42.

**Comment by joelcox** [comment]
@integrii I merged your issue-33 in this repo's branch and then into develop. The problems still persists, but this may be caused by a bad merge on my end. However, develop should be clean now, so if you could try to apply your fix one more time (branching from the new develop) that would be very helpful. Sorry for the trouble! (I added your name to the Thanks section, btw.)

**Comment by integrii** [comment]
Thank you!  I will re-do the change in the new develop branch tomorrow when I get home.  Won't take long.

I will stick around and see how I can contribute.  The project I use this for will surely cause me to write other contributions going forward.

**Comment by joelcox** [comment]
Awesome, thanks again for your work.

**Comment by integrii** [comment]
Pull request created for develop.

**Comment by danhunsaker** [comment]
Still broken, unfortunately...  Seems this one needs a bit more work.

**Comment by integrii** [comment]
Anything I can do to help you?  How many revs are you trying to merge
besides this one?  You are merging into develop right?

**Comment by joelcox** [comment]
Just two. I merged in issue-33, which included a bug fix for the tests that was added in that branch. However, I forgot to merge this branch in develop, on top of which you applied your fix, causing some conflict (because you probably worked in an 'outdated' branch, due to my mistake).

**Comment by joelcox** [comment]
Fixed in 06c5c3f5b656b012b727d44c1b8dcc4751ea9a48.
