### ISSUE TITLE
The library sometimes returns OK when getting data

### ISSUE THREAD

**Issue by integrii** [joelcox/codeigniter-redis#47]
The only place in the library I can find the string 'OK' is in the authentication piece.    It seems like whenever this bug happens, the redis lib will only return OK repeatedly and sometimes "1" for a good few queries.

**Comment by integrii** [comment]
GETDATA: jake:global:homeLocation RETURNED AS OK
jake:global:workLocation RETURNED AS 1
global:internetthreatlevel:threatLevel RETURNED AS OK
jake:weather:isHotTime RETURNED AS OK

**Comment by joelcox** [comment]
OK is a valid status reply from redis-server. What is the exact command you're getting this for?

**Comment by integrii** [comment]
fixed in pull request #48
