### ISSUE TITLE
Unable to connect to redis with a correct password

### ISSUE THREAD

**Issue by Ryan-YJL** [joelcox/codeigniter-redis#49]
I'm having trouble connecting to a remote instance of redis. I have a custom port number and a password. I think it might be a bug.

The thing is I can use the redis-cli on the machine to connect to the port:

redis-cli {portnumber}
-> AUTH {password}
etc..

but I can't connect to when I set the same settings.

$config['redis_host'] = {IP}        // IP address or host
$config['redis_port'] = {portnumber};
$config['redis_password'] = {password};

I thought it could be a port firewall issue but it is not as I deliberately tried an invalid port and got the error.

Could not connect to Redis at {ip}:{port}

which means this is not a port issue.

..with the correct password, I get the error

Could not connect to Redis, invalid password

I have tested the setting without a password and it works.

The password used for my testing was password and has no special characters.

**Comment by Ryan-YJL** [comment]
I managed to connect without a password in the config but with the password set in the auth command.

$config['redis_host'] = {IP}
$config['redis_port'] = {portnumber};
$config['redis_password'] = '';

$this->redis->auth({password});
$this->redis->set('foo', 'bar');
echo $this->redis->get('foo'); 

I am curious as to what is the redis_password used for?

**Comment by danhunsaker** [comment]
It is used in the constructor to attempt to authenticate, as expected, but it checks specifically for the response "OK", which may not be what Redis is returning, in your case.  What versions are you using?  (Redis, PHP, CI, and this library)

**Comment by Ryan-YJL** [comment]
I am using Redis 2.6.16, PHP 5.3.10-1ubuntu3.6, CI 2.1.3, library 0.4.1 .

**Comment by danhunsaker** [comment]
Is that 0.4.1 the tag, or just the version in the library doc block?  Because a lot has been done with auth since that tagged release.  Perhaps the latest master or develop would fix your issue?

**Comment by joelcox** [comment]
Yes, please let us know if the same thing happens when you use the latest master. You don't actually have to call the `_auth` method (or any method prefixed with a `_`. These are called for you.

**Comment by Ryan-YJL** [comment]
I've just updated with the library with the master branch here in github. The config password worked. I've previously downloaded using spark install. I think you need to update the repository there.

I should have tried it earlier :) Thanks.

**Comment by joelcox** [comment]
Sorry for your trouble kicka. I'll update the Spark when the new patch is in.
