### ISSUE TITLE
Redis pipeline - batch get

### ISSUE THREAD

**Issue by eranhazout** [joelcox/codeigniter-redis#55]
Thanks for this great script!
Can you add pipeline or some other "batch get" solution for this script?
I think it will be very helpful for me and others :)

**Comment by danhunsaker** [comment]
There's always `->multi() ... ->exec()`....

**Comment by eranhazout** [comment]
That's great. thanks

**Comment by joelcox** [comment]
Thanks for pitching in @danhunsaker.

**Comment by danhunsaker** [comment]
No problem.  :-)
