### ISSUE TITLE
method _bulk_reply is not returning the correct data

### ISSUE THREAD

**Issue by DaLt0n** [joelcox/codeigniter-redis#57]
Redis protocol sends a "CRLF" when it returns a string with zero length ($0), but when it  returns a string "-1" ($-1) length it does not have a "CRLF". Solution is to remove "CRLF" when its a zero length string.

-- CIRedis::_bulk_reply --
remove:     if ($value_length <= 0) return NULL;
add:        if ($value_length <= 0) {
add:            if ($value_length == 0) {
add:                fgets($this->_connection);
add:            }
add:            return NULL;
add:        }

**Comment by danhunsaker** [comment]
See also #53.

Please submit a PR for this, since you have a fix already figured out.

**Comment by eranhazout** [comment]
Tried that. and now I'm getting null response..

```
    if ($value_length <= 0){
        if ($value_length == 0){
        fgets($this->_connection, $value_length + 1);
        }
        return NULL;
    }
```

**Comment by DaLt0n** [comment]
http://redis.io/topics/protocol
