### ISSUE TITLE
No way to check if redis is running

### ISSUE THREAD

**Issue by roopunk** [joelcox/codeigniter-redis#61]
So when my redis server is not running and I try to initialize the library : `$this->load->library('Redis')` , it throws an error straight away via show_error() CI function which gives a 500 http response code. 

I think It will be great to have a function like getStatus() to check if redis is on and then running the query. So something like : 

``` php
if($this->redis->getStatus()) 
    $this->redis->set($key, $value);
```

**Comment by joelcox** [comment]
Hi roopunk, I can see the value of this feature, but this library is no longer in active development. I don't want to encourage others to keep using this library, so I won't be accepting any pull requests unless there are critical security issues.

**Comment by roopunk** [comment]
Umm, cool. Sorry I just read your issue on deprecating the library. The other alternative you suggested was predis. Can you give a good online resource on integrating predis with CodeIgniter? Or any other library that you might suggest for using inside CI?

**Comment by joelcox** [comment]
Hey Roopunk, Predis should be available via composer. The CodeIgniter site mentions how to enable composer autoload support in de config.

http://www.codeigniter.com/user_guide/general/autoloader.html

A more in-depth tutorial can be found here:

http://avenir.ro/codeigniter-tutorials/codeigniter-with-composer/

**Comment by roopunk** [comment]
Cool. Thanks! :+1:
