### ISSUE TITLE
How can i use this in cli?

### ISSUE THREAD

**Issue by lanber** [joelcox/codeigniter-redis#66]
Hello, thank you for your code, but i have a problem.How can i use this in cli?
My error:
php index.php crons/DymcCodeCron sendMsg

A PHP Error was encountered

Severity:    Warning
Message:     Redis::__construct() expects exactly 0 parameters, 1 given
Filename:    /system/core/Loader.php
Line Number: 1281

Backtrace:
        File: /controllers/crons/DymcCodeCron.php
        Line: 10
        Function: library

        File: /index.php
        Line: 315
        Function: require_once

**Comment by lanber** [comment]
i solved this problem by changing filename of `libraries/Redis.php`

**Comment by meredevelopment** [comment]
@Ianber I realise this is long ago, but do you remember what you changed it to? I've hit the same problem with a newer version of Redis server, current Predis, and an older codebase. Exactly the same error message.
