### ISSUE TITLE
undefined variable

### ISSUE THREAD

**Issue by adulion** [joelcox/codeigniter-redis#7]
i received an undefined variable notice on line 361 of the library- can be fixed by initialising the response variable with an empty array

**Comment by joelcox** [comment]
Heya, I believe this is fixed in the develop branch: https://github.com/joelcox/codeigniter-redis/blob/develop/libraries/Redis.php

**Comment by adulion** [comment]
Thats great, just in case you didn't know.

chris

On Wed, Mar 28, 2012 at 9:42 PM, Jol Cox <
reply@reply.github.com

> wrote:
> 
> Heya, I believe this is fixed in the develop branch:
> https://github.com/joelcox/codeigniter-redis/blob/develop/libraries/Redis.php
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/joelcox/codeigniter-redis/issues/7#issuecomment-4787154

## 

---

Have you signed up for yrecruit.com launch info? - http://yrecruit.com

07771348499 (UK)
00447771348499 (OUTSIDE UK)
skype: aadulion

**Comment by joelcox** [comment]
Thanks for the heads up!
