### ISSUE TITLE
_auth() never reaches show_error() on an authentication error.

### ISSUE THREAD

**Issue by ghost** [joelcox/codeigniter-redis#8]
The `_auth()` method does a very simple check to see if authentication worked:

```
$request = $this->_encode_request('AUTH ' . $password);
if (! $this->_write_request($request))
{
```

In the case of a failed auth attempt, `_write_request()` will still evaluate to 'true' as an error string will be returned (e.g. 'invalid password').

There are three options here:
-  Just call `_write_request()` in `_auth()` and don't care if it works, since failures will be logged anyway
-  Make a `_write_auth_request()` that returns an explicit bool, so people can throw / error if authentication failed
-  Add an `$auth` bool to the existing `_write_request()` to be passed on to `_read_request()` indicating that any failure should return false

I was leaning in the third direction, but wanted some feedback prior to implementing that.

**Comment by joelcox** [comment]
Option 3 seems the most sensible to me, too.

**Comment by ghost** [comment]
I only mentioned option 2 because a lot of people could probably keep going without Redis. Said people, however, are probably smart enough to modify the library not to halt the framework in the constructor or while authenticating :)

**Comment by joelcox** [comment]
True. Don't forget to add yourself to the "thank you" list in the README.

**Comment by ghost** [comment]
Upon reflection, option 3 is actually kind of ugly. It adds a variable to be passed around procedural to a few functions inside of a class that only fixes one corner case.

I'm thinking about just using a class variable `$errno` and setting it high when `_error_reply()` is entered for any reason, while providing a private method that checks and re-sets that variable. That would let `_auth()` know right away if something went wrong, and simply checking the variable would clear it.

I'm sure some use could be found for it in the future, as `_error_reply()` being entered is interesting in every case.

**Comment by joelcox** [comment]
So what about not making this more difficult that it really is and return FALSE on default from `_error_reply()` and `log_message()` the error?

**Comment by ghost** [comment]
:) I need a lot more, or a lot less coffee, I'm just not sure which. Sorry, I was thinking in the context of what I'm working on, which is _not_ a typical use of Redis.

**Comment by ghost** [comment]
Latest pull request (trivial) fixes it. If someone really wants to get at the error context, it would be trivial for them to just add a variable to get it.

**Comment by joelcox** [comment]
Agreed. We shouldn't make this more complicated than it really is ;-). Thanks again.
