### ISSUE TITLE
Problem with special character(SPACE, '!', '%', etc.) in keys and values

### ISSUE THREAD

**Issue by erain** [joelcox/codeigniter-redis#9]
Hi, I just found that this library cannot deal with almost ANY special characters. I was trying to store some JSON within some keys, however I found that nothing passed to the redis.

Then I tried the following with no luck:

```
$this->redis->command('set ' .'key1' . ' ');
$this->redis->command('set ' .'key1' . '!');
$this->redis->command('set ' .'key1' . '%');
```

I think this may due to the key and the value were not proper encoded. Wish this issue report can be a little help.

**Comment by joelcox** [comment]
Hi Erain, you can manually escape characters by surrounding the value (or the key name) with double quotes.

```
$this->redis->command('set foo "bar!"');
```

**Comment by erain** [comment]
Hi joelcox, thanks for this quick reply!

The string I need to store itself contains the " character... More precisely, the string I want to store is a JSON string:

```
{"Antigua and Barbuda":"5.1"}
```

I have tried many times, but it just won't work...

**Comment by joelcox** [comment]
You can probably get away with this by calling PHP's [addslashes](http://php.net/manual/en/function.addslashes.php) function first.
